### ISSUE TITLE
[Patrocinador] Definir los datos a registrar

### ISSUE THREAD

**Issue by macagua** [ScrumLATAMComunidad/scrumlatamcomunidad.com#25]
COMO fundador de la comunidad 
QUIERO registrar los datos de los patrocinadores 
PARA tener una base da datos actualizada

PRE-CONDICION
que no esté registrado.
que tenga una dirección de correo electrónico.
que tenga redes sociales

POST CONDICION
Que reciba  un correo de bienvenida

**Comment by macagua** [comment]
@Hiomara esta tarea esta hecha

**Comment by lmartel0911** [comment]
REGISTRO DE PATRONINADORES
1. Tipo de Patrocinio
2. Nombre de la Empresa o Nombre de Persona
3. Logo (definir un peso máximo) - informativo:  Esto ayudará a identificar visualmente al patrocinador y proporcionará una mayor visibilidad de su participación en la comunidad ágil.
4. Descripción - informativo (Proporciona una descripción breve pero informativa del sponsor. Esto puede incluir información sobre la empresa, su experiencia, sus productos o servicios, su visión, etc.)
5. Enlace Web . informativo: Agrega un enlace directo al sitio web del sponsor. Esto permitirá a los visitantes de la página obtener más información sobre la empresa y explorar sus productos o servicio
6.  Correo electrónico
7.  Teléfono de contacto
8. Niveles de sponsor (DEFINIR)
9. Duración del Patrocinio (DEFINIR)

**Comment by Hiomara** [comment]
@scrumlatam,  Favor definir 
Indicar si se denen considerar las tareas 8 y 9, de ser así completar lo solicitado. 
Para la tarea 10, como te gustaría que se realizará el registro de Sponsor / Patrocidador.

**Comment by macagua** [comment]
@emicmiranda @Hiomara esta tarea esta Lista, se documento en el siguiente enlace https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/wiki/Patrocinantes

Si creen prudente de que todo esta bien, hay que cambiar el status a **Hecho**.

**Comment by macagua** [comment]
@emicmiranda esta tarea ya esta hecha y validada por mi, asi que se cierra
