### ISSUE TITLE
[Miembros] Definir los datos a registrar

### ISSUE THREAD

**Issue by macagua** [ScrumLATAMComunidad/scrumlatamcomunidad.com#26]
COMO fundador de la comunidad 
QUIERO registrar los datos en la pagina web 
PARA tener una base da datos actualizada.

PRE-CONDICION
que no esté registrado.
que tenga una dirección de correo electrónico.
que tenga redes sociales

POST CONDICION
Que reciba  un correo de bienvenida

**Comment by Hiomara** [comment]
@scrumlatam 
Rubén por favor completar esta tarea

**Comment by macagua** [comment]
@Hiomara @emicmiranda Para completar inicialmente esta tarea propongo:

- Título (Sr., Sra., Srto., Srta., Dr. Dra., Prof.)
- Nombres
- Apellidos
- Genero (Femenino, Masculino, Prefiero no indicar)
- Organización
- Dirección
- Número de teléfono
- Dirección de correo electrónico
- Perfil Linkedin
- Perfil Indico
- Perfil Discord
- Skills (Coach Agile, Product Owner, SCRUM Master, Tester, UX Design, Developer, Prefiero no indicar)
- Intereses (Coach Agile, Product Owner, SCRUM Master, Tester, UX Design, Developer, Otro)
- Idiomas (Espanol, Inglés, Portugues)

**Comment by macagua** [comment]
@JuanLP06 estos son los datos a usar para las estructura de datos de Miembros, doy por cerrada esta tarea

**Comment by macagua** [comment]
@JuanLP06 voy a reaperturar la tarea #26 de Miembros por que no te apegaste a los lineamientos de la data de estructura requerida, asi que esta tarea tiene prioridad a resolver, en el siguiente comentario se da la lista de campos especificos que debe llevar el CRUD Miembro  https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/issues/26#issuecomment-1623870036
