### ISSUE TITLE
[Autenticacion] Determinar quienes son los administradores de las redes sociales.

### ISSUE THREAD

**Issue by macagua** [ScrumLATAMComunidad/scrumlatamcomunidad.com#27]
COMO fundador de la comunidad 
QUIERO definir quienes son los administradores de las redes sociales 
PARA brindar los accesos de administradores.

PRECONDICIÓN
que tengan una cuenta registrada

POST CONDICION
se pueda dar acceso con permiso de administrador

**Comment by Hiomara** [comment]
@scrumlatam 
Ruben favor de determinar quines son los administradores de las redes sociales

**Comment by macagua** [comment]
@emicmiranda @Hiomara segun Ruben el es administrador de todas las cuentas de redes sociales, por lo tanto con el se debe canalizar los respectivos accesos para crear las integraciones de redes sociales. Se da por cerrada esta tarea
