### ISSUE TITLE
[Requerimientos] Coordinar reunión con participantes de equipos de la comunidad

### ISSUE THREAD

**Issue by macagua** [ScrumLATAMComunidad/scrumlatamcomunidad.com#29]
COMO fundador de la comunidad 
QUIERO coordinar con representantes de equipos una reunión 
PARA que nos den feedback de sus necesidades para la página web.

PRECONDICIÓN
que las personas convocadas conozcan las necesidades de la comunidad.
que sean personas que pueda tomar decisiones

POST CONDICIÓN
programar fecha de reunión

**Comment by lmartel0911** [comment]
La reunión será el día Jueves 08/06 a las 7pm (hora Perú colombia)

**Comment by macagua** [comment]
@emicmiranda @Hiomara Este tipo de acividades no se reflejan por aca, se da por cerrada y archivada
