### ISSUE TITLE
[Patrocinador] Definir una estructura de base de datos de Patrocinador

### ISSUE THREAD

**Issue by macagua** [ScrumLATAMComunidad/scrumlatamcomunidad.com#31]
Para definir la estructura de base de datos de "Patrocinador", debe:

- [x] Escribir la documentacion en la [wiki](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/wiki) como una nueva pagina.
- [x] Debe escribir el nombre de la clase.
- [x] Debe escribir los nombres de los atributos
- [x] Debe escribir los tipos de los atributos
- [x] Debe escribir los nombres de los comportamientos personalizados
- [x] Debe escribir los tipos de los comportamientos personalizados

**Comment by alfadestroyer** [comment]
@emicmiranda @Hiomara Se escribió la documentación en el siguiente [enlace](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/wiki/Patrocinantes)

**Comment by alfadestroyer** [comment]
@emicmiranda @Hiomara  @macagua esta tarea esta hecha, la dejo en revisión, y si todo esta bien, cambien el status  a "Hecho"

**Comment by macagua** [comment]
@emicmiranda @Hiomara Por parte mi esta bien, si para ustedes esta bien, cambiar el status a **"Hecho"**.

**Comment by macagua** [comment]
@emicmiranda esta tarea ya esta hecha y validada por mi, asi que se cierra
