### ISSUE TITLE
[Requerimientos] Realizar reunión con equipo de la comunidad

### ISSUE THREAD

**Issue by lmartel0911** [ScrumLATAMComunidad/scrumlatamcomunidad.com#35]
COMO equipo técnico
QUIERO reunirme con el equipo de la comunidad
PARA que nos den feedback de sus necesidades para la página web.

PRECONDICIÓN
que las personas convocadas conozcan las necesidades de la comunidad.
que sean personas que pueda tomar decisiones

POST CONDICIÓN
actividades definidas para revisar con el equipo técnico

**Comment by macagua** [comment]
@emicmiranda @Hiomara @lmartel0911  Este tipo de acividades no se reflejan por aca, se da por cerrada y archivada
