### ISSUE TITLE
[Miembros] Estructura de base de datos

### ISSUE THREAD

**Issue by macagua** [ScrumLATAMComunidad/scrumlatamcomunidad.com#57]
Para definir la estructura de base de datos de "Miembros", debe:

- [x] Escribir la documentacion en la [wiki](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/wiki) como una nueva pagina.
- [x] Debe escribir el nombre de la clase.
- [x] Debe escribir los nombres de los atributos
- [x] Debe escribir los tipos de los atributos
- [x] Debe escribir los nombres de los comportamientos personalizados
- [x] Debe escribir los tipos de los comportamientos personalizados

**Comment by macagua** [comment]
@JuanLP06 reporta donde publicaste la wiki con esta tarea

**Comment by macagua** [comment]
@JuanLP06 las ultimas dos tareas **Debe escribir los nombres de los comportamientos personalizados** y 
 **Debe escribir los tipos de los comportamientos personalizados**, marca las casillas ya que de momento yo no veo que se tenga que definir comportamientos personalizados para esta clase, al menos en esta iteracion

**Comment by macagua** [comment]
@JuanLP06 por ultimo cambia al Status **En Revision** para que la vuelva a revisar

**Comment by macagua** [comment]
@JuanLP06 la tarea #57 de Miembros aun no esta lista por que no te apegaste a los lineamientos de la data de estructura requerida, asi que esta tarea tiene prioridad a resolver, en el siguiente comentario se da la lista de campos especificos que debe llevar el CRUD Miembro  https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/issues/26#issuecomment-1623870036

**Comment by JuanLP06** [comment]
@macagua  la wiki agregada es esta: https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/wiki/Miembros

**Comment by macagua** [comment]
@emicmiranda @Hiomara esta tarea se valido su los criterios de aceptacion, esta tarea se da por cerrada, se cambia a Status Hecho.
