### ISSUE TITLE
[Patrocinador] Crear el diagrama de clase

### ISSUE THREAD

**Issue by emicmiranda** [ScrumLATAMComunidad/scrumlatamcomunidad.com#60]
Para crear el diagrama de clase para el formulario de "Patrocinador"

- [x] Usar la definición [PlantUML](https://plantuml.com/class-diagram).
- [x] Generar una imagen del diagrama.
- [x] Generar una Wiki con la documentación del diagrama de clases detallada, adjuntada con soporte gráfico la imagen generada del diagrama. 
- [x] Publicarlo esto entregable en formato con el nombre ``patrocinante.puml`` dentro de directorio [docs](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/tree/develop/docs/source/backend) dentro del codigo fuente del backend.

**Comment by alfadestroyer** [comment]
@emicmiranda @Hiomara @macagua , Se genero la imagen del diagrama de clase

![Image](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/assets/132786011/fcdd1979-f237-4487-8257-b5ea085126df)

**Comment by alfadestroyer** [comment]
@emicmiranda @Hiomara La tarea "Publicarlo esto entregable en formato .puml dentro de directorio [docs](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/tree/master/backend/src/slc_sitioweb) (sino existe debe crearla) dentro del código fuente del backend." por esta lista, solo que dependo de @macagua suba un código para subir lo mio, a continuación muestro el código como genere la imagen.


```
@startuml
class Patrocinante {
   +tipo : String
   +nombre : String
   +logotipo : File
   +descripcion : String
   +url : String
   #email : String
   #telefono : Integer
}
@enduml
```

**Comment by macagua** [comment]
@alfadestroyer ya publique la estructura de documentos:

```
docs/
├── build
├── make.bat
├── Makefile
└── source
    ├── backend
    │   └── index.rst
    ├── conf.py
    ├── index.rst
    ├── _static
    └── _templates

5 directories, 5 files
```

En la ruta ``docs/source/backend/`` vas a crear el archivo ``patrocinante.puml`` al mismo nivel del archivo ``index.rst`` con la estructura de archivo definida en https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/blob/develop/docs/source/backend/index.rst?plain=1#L8

Al terminar cambia el Status a **En Revision**.

**Comment by macagua** [comment]
@emicmiranda @Hiomara esta tarea se valido su los criterios de aceptacion y correcto funcionamiento y se fusiono en la principal de desarrollo

**Comment by alfadestroyer** [comment]
@emicmiranda @macagua Se actualizo la Wiki de esta clase [Community Sponsor](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/wiki/Community-Sponsor)
