### ISSUE TITLE
[Miembros] Crear el diagrama de clase

### ISSUE THREAD

**Issue by emicmiranda** [ScrumLATAMComunidad/scrumlatamcomunidad.com#64]
Para crear el diagrama de clase para el formulario de "Miembros"

- [x] Usar la definición [PlantUML](https://plantuml.com/class-diagram).
- [x] Generar una imagen del diagrama.
- [x] Generar una Wiki con la documentación del diagrama de clases detallada, adjuntada con soporte gráfico la imagen generada del diagrama. 
- [x] Publicarlo esto entregable en formato con el nombre ``miembro.puml`` dentro de directorio [docs](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/tree/develop/docs/source/backend) dentro del codigo fuente del backend.

**Comment by JuanLP06** [comment]
@emicmiranda @Hiomara @macagua , Se genero la imagen del diagrama de clase.
![image](https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/assets/10691487/8976c261-6f51-45fd-82b9-1c0bf7c0c3f9)

Momentaneamente se agrega código de la clase acá, hasta que se cree el repositorio correspondiente.

@startuml
class Miembro{
  +nombre: str
  +apellido: str
  #correo : str
  +username: str
  #telefono: int
  +pais: str
}
@enduml

**Comment by macagua** [comment]
@JuanLP06 ya publique la estructura de documentos:

```
docs/
├── build
├── make.bat
├── Makefile
└── source
    ├── backend
    │   └── index.rst
    ├── conf.py
    ├── index.rst
    ├── _static
    └── _templates

5 directories, 5 files
```

En la ruta ``docs/source/backend/`` vas a crear el archivo ``miembro.puml`` al mismo nivel del archivo ``index.rst`` con la estructura de archivo definida en https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/blob/develop/docs/source/backend/index.rst?plain=1#L14

Al terminar cambia el Status a **En Revision**.

**Comment by JuanLP06** [comment]
@macagua cree un PR para incorporar el archivo "miembro.puml", favor verificar.
https://github.com/ScrumLATAMComunidad/scrumlatamcomunidad.com/blob/JuanLP06-patch-1/docs/source/backend/miembro.puml

**Comment by macagua** [comment]
@emicmiranda @Hiomara esta tarea se valido su los criterios de aceptacion y se fusiono en la principal de desarrollo, esta tarea se da por cerrada, se cambia a Status Hecho. Hecho con commits 9b2a218 y faf7aa0
