### ISSUE TITLE
📃[Contenido] Escribir los contenidos de la seccion "Quienes somos"

### ISSUE THREAD

**Issue by emicmiranda** [ScrumLATAMComunidad/scrumlatamcomunidad.com#68]

**Comment by macagua** [comment]
@emicmiranda Esta tareas esta realizada en el documento de google drive https://docs.google.com/document/d/1ys64LnZGbt6xawbBiU5t15OsukEiglxEnBoMPs9wF2Y/edit?usp=sharing
