### ISSUE TITLE
📃[UX/UI] Hacer UX Research

### ISSUE THREAD

**Issue by macagua** [ScrumLATAMComunidad/scrumlatamcomunidad.com#75]
A continuacion se listas las tareas:

- [x] Producto digital.
- [x] UX Becthmarking.
- [x] User Persona.

**Comment by maxudes** [comment]
@macagua @emicmiranda Acabo de publicar el documento PDF del Benchmarking en la carpeta dek drive, y aqui esta el enlace para su descarga https://drive.google.com/file/d/1gGeCrPMcTdDP6TuzQRjYq1E8tAH5zZs9/view?usp=drive_link

**Comment by maxudes** [comment]
@macagua @emicmiranda el documento que actualmente estamos trabajando es la definición del proyecto como Producto digital, aca esta el documento compartido en el drive en este siguiente enlace https://docs.google.com/document/d/1nC8-hn1tOZchPk2fu9AC0Ukyc4dEC7Coav9h-pKPPWg/edit#heading=h.7m60ffrl6wgc

**Comment by maxudes** [comment]
@macagua @emicmiranda hice la revision en el documento existente en el drive como habia quedado el dia de hoy y deje algunas observaciones, faltan algunos datos a documentar como la cantidad de comunidades de metodologias agiles en latinoameria y Ruben quedo en pasarme ese dato, de igual manera esta pendiente con Leonardo hacer la mejora de los insigns. aca dejo el documento con las observaciones https://docs.google.com/document/d/1nC8-hn1tOZchPk2fu9AC0Ukyc4dEC7Coav9h-pKPPWg/edit Saludos!

**Comment by maxudes** [comment]
@macagua @emicmiranda @Hiomara estan listas estas tareas, las pueden revisar y editar en caso de que lo consideren. Saludos!
